name: Automation
on: [push, pull_request, workflow_dispatch]
jobs:
  ci:
    name: GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run KtLint
        run: bash ./gradlew clean ktlintCheck --refresh-dependencies
      - name: Run Test Suite
        run: bash ./gradlew clean build dokkaHtml test --refresh-dependencies
      - name: Build Generated Documentation
        uses: llvm4j/infrastructure/deploy-to-s3@deploy-to-s3
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          prefix: ${{ env.GITHUB_SHA }}
          directory: build/javadoc
          delete-existing-objects: true