name: Automation
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    name: Check tests and codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run KtLint
        run: bash ./gradlew clean ktlintCheck --refresh-dependencies
      - name: Run Test Suite
        run: bash ./gradlew clean build test --refresh-dependencies